id: I4C0F4FC4
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-15 07:22:18.493555+00:00
last_modified: 2022-12-15 07:22:18.493561+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-091-077
  eft-text-version: 1.1.2 2020
  title: Toh_679-Dharan%C4%AB_Praising_the_Qualities_of_the_Immeasurable_One-v2
bases:
  DFCB:
    source_metadata: null
    order: 1
    base_file: DFCB.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
